// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsUAz_LDjej3z6YK0lHi4Hhvr2Av2yceU',
    appId: '1:577982904760:web:6331eed79b56784ffd774d',
    messagingSenderId: '577982904760',
    projectId: 'dokanmate',
    authDomain: 'dokanmate.firebaseapp.com',
    storageBucket: 'dokanmate.firebasestorage.app',
    measurementId: 'G-W5PYWP5L6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK9cEBi_EXQeAZ2GdVcqT7sUMg8on6_H0',
    appId: '1:577982904760:android:a82b228a4febbe93fd774d',
    messagingSenderId: '577982904760',
    projectId: 'dokanmate',
    storageBucket: 'dokanmate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91-oMG-W4uO2GCZB2XTAVx3eYYS1a_Hc',
    appId: '1:577982904760:ios:b9e2534d33a0c972fd774d',
    messagingSenderId: '577982904760',
    projectId: 'dokanmate',
    storageBucket: 'dokanmate.firebasestorage.app',
    iosBundleId: 'com.appibrium.dokanmateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC91-oMG-W4uO2GCZB2XTAVx3eYYS1a_Hc',
    appId: '1:577982904760:ios:b9e2534d33a0c972fd774d',
    messagingSenderId: '577982904760',
    projectId: 'dokanmate',
    storageBucket: 'dokanmate.firebasestorage.app',
    iosBundleId: 'com.appibrium.dokanmateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsUAz_LDjej3z6YK0lHi4Hhvr2Av2yceU',
    appId: '1:577982904760:web:3f826b4f47701c49fd774d',
    messagingSenderId: '577982904760',
    projectId: 'dokanmate',
    authDomain: 'dokanmate.firebaseapp.com',
    storageBucket: 'dokanmate.firebasestorage.app',
    measurementId: 'G-HGFL1T658V',
  );
}
